### PR TITLE
Make statsd struct public, so that methods show up in godoc

### PR DESCRIPTION
**Pull request by fordhurley**

### CODE REVIEW

**Comment by GeertJohan** [comment]
:+1:

**Comment by peterbourgon** [comment]
The whole point of a private implementation is to obscure the details from the caller. The interface contains everything you need. Can you be a bit more explicit about why you want this?

**Comment by fordhurley** [comment]
The point was not to expose the implementation but to expose the great doc comments you wrote. The other option would be to move the comments to the interface definition.

**Comment by peterbourgon** [comment]
Thanks for this, and sorry for my delay! I made the changes directly in master with a few tweaks. All credit to you.

**Pull request closed without merging**
